"""
Alert Model
SQLAlchemy model for real-time security alerts and AI threat detection events
"""

import enum
import uuid
from typing import Optional, Dict, Any, TYPE_CHECKING
from sqlalchemy import String, Text, Float, Enum as SQLEnum, ForeignKey, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.base import Base, UUIDMixin, TimestampMixin, SoftDeleteMixin

if TYPE_CHECKING:
    from app.models.video import Video
    from app.models.user import User


class AlertSeverity(str, enum.Enum):
    CRITICAL = "critical"
    WARNING = "warning"
    INFO = "info"


class AlertStatus(str, enum.Enum):
    NEW = "new"
    ACKNOWLEDGED = "acknowledged"
    RESOLVED = "resolved"


class Alert(Base, UUIDMixin, TimestampMixin, SoftDeleteMixin):
    """
    Security Alert Event generated by AI vision detections or operational system events.
    """
    __tablename__ = "alerts"

    alert_id: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        unique=True,
        index=True,
        comment="Unique alert reference (e.g. ALT-2026-0812)"
    )

    alert_type: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        index=True,
        comment="Type of event (Person Detected, Restricted Area Event, Camera Offline, etc.)"
    )

    severity: Mapped[AlertSeverity] = mapped_column(
        SQLEnum(AlertSeverity, name="alertseverity"),
        nullable=False,
        default=AlertSeverity.WARNING,
        index=True
    )

    status: Mapped[AlertStatus] = mapped_column(
        SQLEnum(AlertStatus, name="alertstatus"),
        nullable=False,
        default=AlertStatus.NEW,
        index=True
    )

    video_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        ForeignKey("videos.id", ondelete="CASCADE"),
        nullable=True,
        index=True
    )

    camera_name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        default="CAM-01 (Main Gate)"
    )

    timestamp_seconds: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        default=0.0
    )

    detected_object_label: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True
    )

    confidence: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True
    )

    frame_image_url: Mapped[Optional[str]] = mapped_column(
        String(512),
        nullable=True
    )

    assigned_user_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True
    )

    metadata_json: Mapped[Dict[str, Any]] = mapped_column(
        JSON,
        nullable=False,
        default=dict
    )

    def __repr__(self) -> str:
        return f"<Alert(alert_id='{self.alert_id}', type='{self.alert_type}', severity='{self.severity.value}')>"
